### ISSUE TITLE
PopOver is not closing automatically.

### ISSUE THREAD

**Issue by MishraTanishq619** [sujjeee/nextjs-dnd#1]
![Screenshot from 2024-06-07 09-30-32](https://github.com/sujjeee/nextjs-dnd/assets/127047332/311c6aa7-c1cc-46f6-8136-c1a8250fd63b)

Issue:
The popOver should be closed after the "Submit" button is clicked.

**Comment by sujjeee** [comment]
You can use 'useState' to handle dialog close and open state.
